bot_url: "https://t.me/WaitArtistBot"

messages:
  response:
    start: "Привет, бот поможет тебе узнавать о том когда, твои любимы группы/артисты будут в выступать в твоем городе \n
      Для этого выполни команды ниже: \n
      /search - поиск артиста для подписки \n
      /set_up_city - указать свой город (нужно, чтобы слать оповещения, когда группа/артист будут в твоем городе) \n"
    search: "Введите группу/артиста, на которого хотите подписаться"
    select_artist: "Выберите из прдложенных групп/артистов"
    subscription_already_exists: "Вы уже были подписаны ранее"
    subsscription_succesfully_added: "Вы успешно подписались на группу/артиста"
    set_up_city: "Введите город, в котором вы живете"  
    unknown_command: "Неизвестная команда/запрос"
  error:
    unknown_artist: "Извините, группа/артист не найдены"
    default: "Что-то пошло не так"
    unknown_city: "Извините, город не найден в базе"
