bot_url: "https://t.me/WaitArtistBot"

messages:
  response:
    start: "Привет, бот поможет тебе узнавать о том когда, твои любимы группы/артисты будут в выступать в твоем городе \n
      Для этого выполни команды ниже: \n
      /search - поиск артиста для подписки \n
      /set_up_city - указать свой город (нужно, чтобы слать оповещения, когда группа/артист будут в твоем городе) \n
      /events - список ближаийших событий в вашем городе \n
      /help - список команд \n
      "
    search: "Введите группу/артиста, на которого хотите подписаться"
    select_artist: "Выберите из предложенных групп/артистов"
    subscription_already_exists: "Вы уже были подписаны ранее"
    subsscription_succesfully_added: "Вы успешно подписались на группу/артиста"
    set_up_city: "Введите город, в котором вы живете"  
    select_city: "Выберите из предложенных городов"
    city_setting_up_is_succesfull: "Город успешно сохранен"
    unknown_command: "Неизвестная команда/запрос"
    show_events: "События в вашем городе:"

  error:
    unknown_artist: "Извините, группа/артист не найдены"
    default: "Что-то пошло не так"
    unknown_city: "Извините, город не найден в базе"
    city_has_not_been_set: "Город еще не указан, пожалуйста введите /set_up_city, чтобы указать свой город"
    artists_have_not_been_set: "У вас нет подписок на группу/артиста введите /search для подписки на артиста"
    events_not_found: "Ближайшие события в вашем городе для артистов, на которые вы подписаны не найдены"
