bot_url: "https://t.me/WaitArtistBot"

messages:
  response:
    start: "Привет, бот поможет тебе узнавать о том когда, твои любимы групппы/артисты будут в выступать в твоем городе \n
      Для этого выполни команды ниже: \n
      /search - поиск артиста для подписки \n
      /set_up_city - указать свой город (нужно, чтобы слать оповещения, когда группа/артист будут в твоем городе) \n"
    search: "Введите группу/артиста, на которого хотите подписаться"
    set_up_city: "Введите город, в котором вы живете"  
    unknown_command: "Uknown command."
    unknown_artist: "Извините, группа/артист не найдены"
    unknown_city: "Извините, город не найден в базе"
  error:
    default: "Что-то пошло не так"